import Head from "next/head";
import { NextPageWithLayout } from "./_app";
import MainLayout from "@/components/layouts/MainLayout";
import useToast from "@/components/common/Toast";
import Button from "@/components/common/Button";

const Home: NextPageWithLayout = () => {
  const { ToastContainer, addToast } = useToast();
  return (
    <>
      <Head>
        <title>Home - MEONO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <div>
        <Button
          onClick={() => {
            addToast("Hello", "success");
          }}
        >
          Hello
        </Button>
      </div>
      <ToastContainer />
    </>
  );
};

Home.getLayout = (page) => <MainLayout>{page}</MainLayout>;

export default Home;
